version: '3.4'

services:
  decide:
    container_name: decision
    image: decider
    build:
      context: .
      dockerfile: ./Dockerfile
    
    volumes:
      - /home/jack/demo/data:/app/data
    
    entrypoint: ["python", "classifer.py"]
